### PR TITLE
Tweak intro

### PR DESCRIPTION
**Pull request by sogaiu**

### CODE REVIEW

**Comment by borkdude** [comment]
@sogaiu What did you change?

**Comment by sogaiu** [comment]
Ah sorry, didn't realize that being one line it would be hard to spot the changes, should have looked closer :)

it's -> its
JVM-byte code -> JVM bytecode
`defrecord`, `defprotocol` -> `deftype`, `definterface`

**Comment by borkdude** [comment]
@sogaiu Thanks.

**Comment by borkdude** [comment]
Can you take a look at https://github.com/babashka/book/blob/master/CONTRIBUTING.md and include your name as written there? The reason for this is similar to https://github.com/clojure-cookbook/clojure-cookbook. If the book ever gets printed or sold as PDF etc. I don't want to have any problems with intellectual property rights from other people.

**Comment by sogaiu** [comment]
I looked before making the PR but thought what I wrote was so minor I didn't think it applied.

I'll take a look again and follow the instructions.

**Comment by borkdude** [comment]
@sogaiu You're right, this is minor enough.

**Comment by sogaiu** [comment]
If I make a significant contribution at some point, I'll take a look at the instructions and consider following them.

Does that sound ok?

**Comment by borkdude** [comment]
It does, thanks!

**Pull request merged**
