### PR TITLE
Add snippet to setup fish shell completion for tabs

### PR DESCRIPTION
**Pull request by prestancedesign**

### CODE REVIEW

**Comment by borkdude** [comment]
@prestancedesign Cool! Is it possible to also add `files` to this so you get autocompletions for local files when you want to execute `bb foo.clj`?

The zsh example has this, but in fish I see:

``` fish
root@08b4598a93bf /# cat bb.edn
{:tasks {a 1 b 2 ceeee 3}}
root@08b4598a93bf /# bb a
a  (List tasks)  b  (List tasks)  ceeee  (List tasks)
```

**Comment by borkdude** [comment]
It seems removing `-f` does the trick. Maybe renaming `List tasks` to `tasks` is nicer in the output?

**Comment by borkdude** [comment]
I just merged it, tweaks can be made later :)

**Comment by prestancedesign** [comment]
When removing `-f`, <TAB> list files but I don't see how to group tasks first and then file listing.
Everything is mixed up.
Is this suitable?

image

**Comment by borkdude** [comment]
I do think this is the correct behavior, although having the tasks first would certainly be nicer.

**Pull request merged**
