### PR TITLE
Add snippet to setup fish shell completion for tabs

### PR DESCRIPTION
**Pull request by prestancedesign**

### CODE REVIEW

**Comment by borkdude** [comment]
@prestancedesign Could you do a separate PR to follow up on https://github.com/babashka/book/blob/master/CONTRIBUTING.md first?

**Comment by borkdude** [comment]
Thanks! Does this autocomplete when you type `bb<space><TAB>` or when you type `bb tasks<TAB>`?

**Comment by prestancedesign** [comment]
Yes, you're right.
Do you know if it's possible to edit a PR before merging?

**Comment by borkdude** [comment]
@prestancedesign Not sure what you're asking? You can push another commit to the branch and the PR will then update itself.

**Pull request closed without merging**
